print("Ingrese la primera nota")
notaa = float(input())
print("Ingrese la segunda nota")
notab = float(input())
print("Ingrese la tercera nota")
notac = float(input())
promedio = round(((notaa + notab + notac) / 3),2)
print("El promedio es: ", promedio)